# fly.toml app configuration file generated for proud-silence-2053 on 2023-07-19T10:08:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proud-silence-2053"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
