### get all blogs
GET http://localhost:3001/api/blogs

### get blogs with query string
GET http://localhost:3001/api/blogs?search=react

### create blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtpa2VAbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjg5NzYyMzg3fQ.Ws1aYPS8qXo3nrKoAbNBE4EGTHF1G3VKS1RDA_jvYRg

{
  "author": "Facebook",
  "url": "www.facebook.com",
  "title": "React Documentation",
  "likes": "3500",
  "year":  "2022"
}

### delete blog
DELETE http://localhost:3001/api/blogs/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtpa2VAbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjg5NzYyMzg3fQ.Ws1aYPS8qXo3nrKoAbNBE4EGTHF1G3VKS1RDA_jvYRg