# token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtpa2UyIiwiaWQiOjIsImlhdCI6MTY4OTY5OTA4N30.JZINJQF_cGa6eBPWGL48V_FBe6WHWtCJKORnvVf7a3U

GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtpa2VAbWFpbC5jb20iLCJpZCI6MywiaWF0IjoxNjg5NzAyOTI5fQ.RyfXDOgI5-C5psAyvDtzynAJH5hNMJwsK3t8dL4J6Hg

{
  "author": "kike",
  "url": "kike.com",
  "title": "another blog",
  "likes": "20"
}

###
DELETE http://localhost:3001/api/blogs/4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtpa2VAbWFpbC5jb20iLCJpZCI6MywiaWF0IjoxNjg5NzAyOTI5fQ.RyfXDOgI5-C5psAyvDtzynAJH5hNMJwsK3t8dL4J6Hg